---
- name: Configure sshd
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: [Reload sshd]

# Fix problem when sshd cannot start because network
# interface is not yet up
- name: Fix sshd systemd unit
  lineinfile:
    path: /etc/systemd/system/sshd.service
    regexp: After=network.target auditd.service
    line: After=network-online.target auditd.service
  notify: [Reload systemd daemon]
