---
- name: Remove garbage packages
  apt:
    state: absent
    name:
      - cloud-init
      - snapd
  notify: [Autoremove packages]

- name: Remove garbage configs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cloud
    - /var/lib/cloud
    - /snap
    - /var/snap
    - /var/lib/snapd

- name: Install basic tools
  apt:
    state: present
    name:
      - man
      - less
      - vim
      - jq
      - python3-pip
